options:
  logging: CLOUD_LOGGING_ONLY

steps:
#Paso 0: Construye la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-first-api', '.']

#Paso 1: Sube la imagen a Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-first-api']

#Paso 2: Despliega la imagen en Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'my-first-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/my-first-api'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
